import { Service, ServiceRequest } from "./types";

export const services: Service[] = [
  {
    id: "maintenance",
    name: "الصيانة الدورية",
    description: "تغيير الزيت والفلاتر وفحص السوائل والتجهيزات الأساسية للسيارة",
    priceRange: "180 – 450",
    timeRange: "2 – 4 ساعات",
    icon: "🔧",
  },
  {
    id: "pre-purchase",
    name: "فحص قبل الشراء",
    description: "فحص شامل للسيارة المستعملة قبل اتخاذ قرار الشراء",
    priceRange: "250 – 500",
    timeRange: "1 – 3 ساعات",
    icon: "🔍",
  },
  {
    id: "ac",
    name: "التكييف",
    description: "صيانة وإصلاح منظومة التكييف وإعادة شحن الغاز",
    priceRange: "150 – 700",
    timeRange: "2 – 6 ساعات",
    icon: "❄️",
  },
  {
    id: "electrical",
    name: "الكهرباء والبطارية",
    description: "فحص الأعطال الكهربائية واستبدال البطارية وإصلاح الأسلاك",
    priceRange: "120 – 600",
    timeRange: "1 – 4 ساعات",
    icon: "⚡",
  },
  {
    id: "tires",
    name: "الإطارات",
    description: "تغيير وموازنة وضبط زوايا الإطارات مع توفير أفضل الماركات",
    priceRange: "80 – 1,200",
    timeRange: "1 – 3 ساعات",
    icon: "🔄",
  },
  {
    id: "accessories",
    name: "الزينة والإكسسوارات",
    description: "تركيب الإكسسوارات وتغليف السيارة وتحسين المظهر الخارجي والداخلي",
    priceRange: "100 – 1,500",
    timeRange: "2 – 8 ساعات",
    icon: "✨",
  },
  {
    id: "detailing",
    name: "التلميع والعناية",
    description: "تلميع احترافي وغسيل عميق وحماية الطلاء لمظهر كالجديد",
    priceRange: "250 – 1,200",
    timeRange: "3 – 8 ساعات",
    icon: "💎",
  },
  {
    id: "bodywork",
    name: "السمكرة والدهان",
    description: "إصلاح الخدوش والحوادث وإعادة الدهان باحترافية عالية",
    priceRange: "يحدد بعد الفحص",
    timeRange: "1 – 5 أيام",
    priceNote: "يحدد بعد الفحص",
    icon: "🎨",
  },
];

export const mockRequests: ServiceRequest[] = [
  {
    id: "REQ-001",
    name: "عبدالله المطيري",
    phone: "0501234567",
    city: "الرياض",
    neighborhood: "حي النخيل",
    carType: "تويوتا",
    carModel: "كامري 2022",
    service: "الصيانة الدورية",
    problemDescription: "موعد صيانة دورية، تغيير زيت وفلاتر",
    carMovable: "نعم",
    preferredTime: "غداً الصباح",
    status: "قيد التنفيذ",
    createdAt: "2026-05-26",
    estimatedPrice: "180 – 450 SAR",
  },
  {
    id: "REQ-002",
    name: "محمد الغامدي",
    phone: "0559876543",
    city: "جدة",
    neighborhood: "حي الزهراء",
    carType: "هوندا",
    carModel: "أكورد 2020",
    service: "التكييف",
    problemDescription: "التكييف لا يبرد بشكل كافٍ",
    carMovable: "نعم",
    preferredTime: "هذا الأسبوع",
    status: "بانتظار موافقة العميل",
    createdAt: "2026-05-25",
    estimatedPrice: "150 – 700 SAR",
  },
  {
    id: "REQ-003",
    name: "سارة الشمري",
    phone: "0541112233",
    city: "الدمام",
    neighborhood: "حي الفيصلية",
    carType: "لكزس",
    carModel: "ES 350 2023",
    service: "التلميع والعناية",
    problemDescription: "تلميع شامل وحماية طلاء",
    carMovable: "نعم",
    preferredTime: "نهاية الأسبوع",
    status: "جديد",
    createdAt: "2026-05-27",
    estimatedPrice: "250 – 1,200 SAR",
  },
  {
    id: "REQ-004",
    name: "فهد العتيبي",
    phone: "0508887766",
    city: "الخبر",
    neighborhood: "حي الثقبة",
    carType: "BMW",
    carModel: "X5 2021",
    service: "السمكرة والدهان",
    problemDescription: "إصلاح خدش في الباب الأمامي الأيسر",
    carMovable: "نعم",
    preferredTime: "الأسبوع القادم",
    status: "قيد الفحص",
    createdAt: "2026-05-24",
    estimatedPrice: "يحدد بعد الفحص",
  },
  {
    id: "REQ-005",
    name: "نورة السبيعي",
    phone: "0534445566",
    city: "الرياض",
    neighborhood: "حي الملقا",
    carType: "نيسان",
    carModel: "باترول 2019",
    service: "الكهرباء والبطارية",
    problemDescription: "السيارة لا تشتعل، مشكلة في البطارية",
    carMovable: "لا",
    preferredTime: "اليوم إن أمكن",
    status: "جاهز للتسليم",
    createdAt: "2026-05-23",
    estimatedPrice: "120 – 600 SAR",
  },
  {
    id: "REQ-006",
    name: "خالد الدوسري",
    phone: "0566778899",
    city: "جدة",
    neighborhood: "حي السلامة",
    carType: "مرسيدس",
    carModel: "C200 2022",
    service: "فحص قبل الشراء",
    problemDescription: "فحص السيارة قبل الشراء من معرض",
    carMovable: "نعم",
    preferredTime: "الغد",
    status: "مكتمل",
    createdAt: "2026-05-22",
    estimatedPrice: "250 – 500 SAR",
  },
];

export const cities = ["الرياض", "جدة", "الدمام", "الخبر"];

export const requestStatuses = [
  "جديد",
  "قيد الفحص",
  "بانتظار موافقة العميل",
  "قيد التنفيذ",
  "جاهز للتسليم",
  "مكتمل",
] as const;
